name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt install gcc doxygen texlive graphviz
    - uses: actions/checkout@v2
    - name: Report versions
      run: |
        make --version
        gcc --version
        doxygen --version
    - name: Build and Test
      run: make -j